let date = new Date()
console.log(date)

let date2 = Date.now() // output will be in epoch time milliseconds
console.log(date2)

// method:
/**
 * getDate()
 * getDay()
 * getFullYear()
 * getHours()
 * getMilliseconds()
 * getMonth()
 * getMinutes()
 * getSeconds()
 * getTime()
 * getTimezoneOffset()
 * getUTCDate()
 * getUTCDay()
 * getUTCFullYear()
 * getUTCHours()
 * getUTCMilliseconds()
 * getUTCMonth()
 * getUTCMinutes()
 * getUTCSeconds()
 * getYear()
 * 
 * setDate()
 * setFullYear()
 * setHours()
 * setMilliseconds()
 * setMinutes()
 * setMonth()
 * setSeconds()
 * setTime()
 * setUTCDate()
 * setUTCFullYear()
 * setUTCHours()
 * setUTCMilliseconds()
 * setUTCMinutes()
 * setUTCMonth()
 * setUTCSeconds()
 * setYear()
 * 
 * toDateString
 * toGMTString()
 * toISOString()
 * toJSON()
 * toLocalDateString()
 * toLocalString()
 * toLocalTimeString()
 * toString()
 * toTimeString()
 * toUTCString()
 * valueOf()
 */